version: "3"
services:
  mariadb:
    image: mariadb:10.6
    container_name: cabi_db
    restart: always
    environment:
      MARIADB_DATABASE: cabi
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - "13306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:alpine
    container_name: cabi_redis
    ports:
      - "6379:6379"
    environment:
      TZ: ${TZ}
