server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

spring:
  config:
    import: optional:file:src/main/resources/secret.properties

  application:
    name: 42cabi-gyeongsan

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/cabi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      client:
        registration:
          42:
            client-id: ${FT_CLIENT_ID}
            client-secret: ${FT_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: public
            client-name: 42 gyeongsan
        provider:
          42:
            authorization-uri: https://api.intra.42.fr/oauth/authorize
            token-uri: https://api.intra.42.fr/oauth/token
            user-info-uri: https://api.intra.42.fr/v2/me
            user-name-attribute: login

management:
  endpoints:
    web:
      exposure:
        include: health, info, graphics, metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${jwt.secret}

slack:
  token: ${SLACK_BOT_TOKEN}
