spring:
  config:
    # ğŸ‘‡ secret.properties íŒŒì¼ ë¡œë“œ
    import: optional:file:src/main/resources/secret.properties

  application:
    name: 42cabi-gyeongsan

  # ğŸ‘‡ [Ver 2.0] Redis ì„¤ì •
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # ğŸ‘‡ íƒ€ì„ì¡´ ì„¤ì • ìœ ì§€
    url: jdbc:mariadb://localhost:13306/cabi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # username, passwordëŠ” secret.propertiesì—ì„œ ê°€ì ¸ì˜´

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      client:
        registration:
          42:
            # ğŸ‘‡ secret.propertiesì˜ ë³€ìˆ˜ ì‚¬ìš©
            client-id: ${FT_CLIENT_ID}
            client-secret: ${FT_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: public
            client-name: 42 gyeongsan
        provider:
          42:
            authorization-uri: https://api.intra.42.fr/oauth/authorize
            token-uri: https://api.intra.42.fr/oauth/token
            user-info-uri: https://api.intra.42.fr/v2/me
            user-name-attribute: login

# ğŸ‘‡ [Ver 2.5] Actuator ëª¨ë‹ˆí„°ë§ ì„¤ì •
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

# ğŸ‘‡ [Ver 3.0 ì¶”ê°€] JWT ë¹„ë°€í‚¤ ì—°ê²° (secret.properties ê°’ ì‚¬ìš©)
jwt:
  secret: ${jwt.secret}

slack:
  token: ${SLACK_BOT_TOKEN}